version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/backend"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/backend"
      - "/frontend"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
