/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_auth_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/{account_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Account Connection */
        post: operations["test_account_connection_api_auth_accounts__account_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin */
        post: operations["begin_api_auth__provider__begin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_auth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete_api_auth__provider__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Migrations */
        get: operations["list_migrations_api_migrations_get"];
        put?: never;
        /** Create Migration */
        post: operations["create_migration_api_migrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preflight Migration */
        post: operations["preflight_migration_api_migrations_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Aggregate Migration Stats */
        get: operations["get_aggregate_migration_stats_api_migrations_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Migration */
        get: operations["get_migration_api_migrations__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Migration Events */
        get: operations["migration_events_api_migrations__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Migration Items */
        get: operations["get_migration_items_api_migrations__job_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/items/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Migration Items */
        post: operations["review_migration_items_api_migrations__job_id__items_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Migration Item */
        post: operations["review_migration_item_api_migrations__job_id__items__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Migration Report */
        get: operations["download_migration_report_api_migrations__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Migration Stats */
        get: operations["get_migration_stats_api_migrations__job_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Playlists */
        get: operations["list_playlists_api_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playlist */
        get: operations["get_playlist_api_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountHistoryView */
        AccountHistoryView: {
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Display Name */
            display_name?: string | null;
            /** Id */
            id: string;
        };
        /** AccountView */
        AccountView: {
            /** Display Name */
            display_name?: string | null;
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Provider User Id */
            provider_user_id?: string | null;
        };
        /** AggregateMigrationStatsView */
        AggregateMigrationStatsView: {
            counts: components["schemas"]["StatusCounts"];
            /**
             * Empty
             * @default false
             */
            empty: boolean;
            /** Message */
            message?: string | null;
            /** Source Provider */
            source_provider?: string | null;
            /** Target Provider */
            target_provider?: string | null;
            /**
             * Total Migrations
             * @default 0
             */
            total_migrations: number;
            /**
             * Total Playlists
             * @default 0
             */
            total_playlists: number;
        };
        /** AuthChallenge */
        AuthChallenge: {
            /** Form Schema */
            form_schema?: {
                [key: string]: unknown;
            } | null;
            /** Instructions */
            instructions?: string | null;
            /** Poll Interval S */
            poll_interval_s?: number | null;
            /** Redirect Url */
            redirect_url?: string | null;
            shape: components["schemas"]["ChallengeShape"];
            /** State */
            state?: string | null;
            /** User Code */
            user_code?: string | null;
            /** Verification Url */
            verification_url?: string | null;
        };
        /** BatchReview */
        BatchReview: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "skip";
            /**
             * Item Ids
             * @default []
             */
            item_ids: string[];
        };
        /**
         * ChallengeShape
         * @description The three UI shapes every auth flow collapses into.
         * @enum {string}
         */
        ChallengeShape: "redirect" | "device_code" | "form";
        /** ConnectionTestView */
        ConnectionTestView: {
            /** Account Id */
            account_id: string;
            /** Message */
            message: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /** ConnectionView */
        ConnectionView: {
            account: components["schemas"]["AccountView"];
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /** CreateMigration */
        CreateMigration: {
            /**
             * Acknowledge Warnings
             * @default false
             */
            acknowledge_warnings: boolean;
            selection: components["schemas"]["Selection"];
            /** Source Account Id */
            source_account_id: string;
            /** Source Provider */
            source_provider: string;
            /** Target Account Id */
            target_account_id: string;
            /** Target Provider */
            target_provider: string;
        };
        /** Credit */
        Credit: {
            /** Instrument */
            instrument?: string | null;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Uri */
            uri?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobItemView */
        JobItemView: {
            /** Album */
            album?: string | null;
            /** Artist */
            artist: string;
            /** Confidence */
            confidence?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Explicit */
            explicit?: boolean | null;
            /** Id */
            id: string;
            /** Isrc */
            isrc?: string | null;
            /** Position */
            position: number;
            /** Reason */
            reason?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Review Action */
            review_action?: ("approve" | "skip") | null;
            /** Review Original Reason */
            review_original_reason?: string | null;
            /** Review Original Status */
            review_original_status?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: unknown;
            };
            /** Source Playlist Id */
            source_playlist_id: string;
            /** Source Playlist Name */
            source_playlist_name?: string | null;
            /** Status */
            status: string;
            /** Target Playlist Id */
            target_playlist_id?: string | null;
            /** Target Uri */
            target_uri?: string | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** JobView */
        JobView: {
            /**
             * Done
             * @default 0
             */
            done: number;
            /** Error */
            error?: string | null;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Id */
            id: string;
            /** Source Provider */
            source_provider: string;
            /** Status */
            status: string;
            /** Target Provider */
            target_provider: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "track" | "episode" | "video" | "local_file" | "unknown";
        /** MigrationOptionView */
        MigrationOptionView: {
            /** Created At */
            created_at?: string | null;
            /**
             * Detail Available
             * @default true
             */
            detail_available: boolean;
            /** Detail Expires At */
            detail_expires_at?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Outcome */
            outcome?: string | null;
            /** Playlist Names */
            playlist_names?: string[];
            /** Source Provider */
            source_provider: string;
            /** Status */
            status: string;
            /** Target Provider */
            target_provider: string;
        };
        /** MigrationStatsView */
        MigrationStatsView: {
            /** Completed At */
            completed_at?: string | null;
            counts: components["schemas"]["StatusCounts"];
            /** Created At */
            created_at?: string | null;
            /**
             * Detail Available
             * @default true
             */
            detail_available: boolean;
            /** Detail Expires At */
            detail_expires_at?: string | null;
            /** Detail Purged At */
            detail_purged_at?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /**
             * Empty
             * @default false
             */
            empty: boolean;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Message */
            message?: string | null;
            /** Outcome */
            outcome?: string | null;
            /**
             * Playlist Count
             * @default 0
             */
            playlist_count: number;
            /** Playlist Names */
            playlist_names?: string[];
            /** Playlists */
            playlists?: components["schemas"]["PlaylistStatsView"][];
            /**
             * Retention Days
             * @default 0
             */
            retention_days: number;
            source_account?: components["schemas"]["AccountHistoryView"] | null;
            /** Source Provider */
            source_provider: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            target_account?: components["schemas"]["AccountHistoryView"] | null;
            /** Target Provider */
            target_provider: string;
            /** Warnings */
            warnings?: {
                [key: string]: string;
            }[];
        };
        /** MigrationWarningsView */
        MigrationWarningsView: {
            /**
             * Code
             * @default migration_warnings
             */
            code: string;
            /**
             * Message
             * @default Review and acknowledge migration warnings before starting.
             */
            message: string;
            /**
             * Warnings
             * @default []
             */
            warnings: {
                [key: string]: string;
            }[];
        };
        /** Playlist */
        Playlist: {
            /** Created At */
            created_at?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id?: string | null;
            /** @default standard */
            kind: components["schemas"]["PlaylistKind"];
            /** Name */
            name: string;
            /** Owner Id */
            owner_id?: string | null;
            /** Photo */
            photo?: string | null;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /** Tracks */
            tracks?: components["schemas"]["Track"][];
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * PlaylistKind
         * @enum {string}
         */
        PlaylistKind: "standard" | "liked_tracks";
        /**
         * PlaylistRef
         * @description Lightweight handle returned while listing, before full read.
         */
        PlaylistRef: {
            /** Collaborative */
            collaborative?: boolean | null;
            /** Id */
            id: string;
            /** @default standard */
            kind: components["schemas"]["PlaylistKind"];
            /**
             * Migrated Track Count
             * @default 0
             */
            migrated_track_count: number;
            /** Migration Note */
            migration_note?: string | null;
            /** Migration Status */
            migration_status?: string | null;
            /** Name */
            name: string;
            /** Owner Id */
            owner_id?: string | null;
            /** Remaining Track Count */
            remaining_track_count?: number | null;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /** Track Count */
            track_count?: number | null;
            /** Tracks Href */
            tracks_href?: string | null;
        };
        /** PlaylistStatsView */
        PlaylistStatsView: {
            counts: components["schemas"]["StatusCounts"];
            /** Source Playlist Id */
            source_playlist_id: string;
            /** Source Playlist Name */
            source_playlist_name?: string | null;
            /** Target Playlist Id */
            target_playlist_id?: string | null;
        };
        /** ProviderView */
        ProviderView: {
            /** Auth Kind */
            auth_kind: string;
            /** Can Source */
            can_source: boolean;
            /** Can Target */
            can_target: boolean;
            /** Display Name */
            display_name: string;
            /** Has Isrc */
            has_isrc: boolean;
            /** Name */
            name: string;
            /** Official */
            official: boolean;
            /** Stability */
            stability: string;
            /** Warning */
            warning?: string | null;
        };
        /** ReviewItem */
        ReviewItem: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "skip";
            /** Target Uri */
            target_uri?: string | null;
        };
        /** Selection */
        Selection: {
            /**
             * Playlist Ids
             * @default []
             */
            playlist_ids: string[];
            /**
             * Tracks
             * @default {}
             */
            tracks: {
                [key: string]: string[];
            };
        };
        /** StatusCounts */
        StatusCounts: {
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Matched
             * @default 0
             */
            matched: number;
            /**
             * Needs Review
             * @default 0
             */
            needs_review: number;
            /** Other */
            other?: {
                [key: string]: number;
            };
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Written
             * @default 0
             */
            written: number;
        };
        /**
         * Track
         * @description A single playlist item in universal form.
         *
         *     Only ``title`` and ``artist`` are strictly required; ``isrc`` is the primary
         *     cross-provider match key when present.
         */
        Track: {
            /** Added At */
            added_at?: string | null;
            /** Album */
            album?: string | null;
            /** Artist */
            artist: string;
            /** Artwork Uri */
            artwork_uri?: string | null;
            /** Composer */
            composer?: string | null;
            /** Credits */
            credits?: components["schemas"]["Credit"][];
            /** Disc Number */
            disc_number?: number | null;
            /** Duration S */
            duration_s?: number | null;
            /** Explicit */
            explicit?: boolean | null;
            /** Genre */
            genre?: string | null;
            /** Id */
            id?: string | null;
            /**
             * Is Local
             * @default false
             */
            is_local: boolean;
            /** Isrc */
            isrc?: string | null;
            /** Label */
            label?: string | null;
            /** @default track */
            media_type: components["schemas"]["MediaType"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Migrated Target Playlist Id */
            migrated_target_playlist_id?: string | null;
            /** Migrated Target Uri */
            migrated_target_uri?: string | null;
            /** Migration Status */
            migration_status?: string | null;
            /** Position */
            position?: number | null;
            /** Provider Uris */
            provider_uris?: {
                [key: string]: string;
            };
            /** Release Date */
            release_date?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Source Item Id */
            source_item_id?: string | null;
            /** Title */
            title: string;
            /** Track Number */
            track_number?: number | null;
            /** Unsupported Reason */
            unsupported_reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_auth_accounts_get: {
        parameters: {
            query?: {
                user_id?: string;
                provider?: string | null;
                check?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_account_connection_api_auth_accounts__account_id__test_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_api_auth__provider__begin_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthChallenge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_auth__provider__callback_get: {
        parameters: {
            query?: {
                user_id?: string;
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_api_auth__provider__complete_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_migrations_api_migrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationOptionView"][];
                };
            };
        };
    };
    create_migration_api_migrations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMigration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_migration_api_migrations_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMigration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationWarningsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aggregate_migration_stats_api_migrations_stats_get: {
        parameters: {
            query?: {
                source_provider?: string | null;
                target_provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateMigrationStatsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_migration_api_migrations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    migration_events_api_migrations__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_migration_items_api_migrations__job_id__items_get: {
        parameters: {
            query?: {
                source_playlist_id?: string | null;
                status?: string[] | null;
                min_confidence?: number | null;
                max_confidence?: number | null;
                reason?: string | null;
                title?: string | null;
                artist?: string | null;
                problem_only?: boolean;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItemView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_migration_items_api_migrations__job_id__items_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItemView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_migration_item_api_migrations__job_id__items__item_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewItem"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_migration_report_api_migrations__job_id__report_get: {
        parameters: {
            query?: {
                format?: "csv" | "json";
                scope?: "all" | "problems";
                source_playlist_id?: string | null;
                status?: string[] | null;
                min_confidence?: number | null;
                max_confidence?: number | null;
                reason?: string | null;
                title?: string | null;
                artist?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_migration_stats_api_migrations__job_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationStatsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_playlists_api_playlists_get: {
        parameters: {
            query: {
                provider: string;
                account_id: string;
                target_provider?: string | null;
                target_account_id?: string | null;
                refresh?: boolean;
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playlist_api_playlists__playlist_id__get: {
        parameters: {
            query: {
                provider: string;
                account_id: string;
                target_provider?: string | null;
                target_account_id?: string | null;
                refresh?: boolean;
                user_id?: string;
            };
            header?: never;
            path: {
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
