/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin */
        post: operations["begin_api_auth__provider__begin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_auth_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/{account_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Account Connection */
        post: operations["test_account_connection_api_auth_accounts__account_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete_api_auth__provider__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_auth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Playlists */
        get: operations["list_playlists_api_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playlist */
        get: operations["get_playlist_api_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Migrations */
        get: operations["list_migrations_api_migrations_get"];
        put?: never;
        /** Create Migration */
        post: operations["create_migration_api_migrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preflight Migration */
        post: operations["preflight_migration_api_migrations_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Aggregate Migration Stats */
        get: operations["get_aggregate_migration_stats_api_migrations_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Migration Stats */
        get: operations["get_migration_stats_api_migrations__job_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Migration */
        get: operations["get_migration_api_migrations__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Migration Items */
        get: operations["get_migration_items_api_migrations__job_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Migration Item */
        post: operations["review_migration_item_api_migrations__job_id__items__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/items/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Migration Items */
        post: operations["review_migration_items_api_migrations__job_id__items_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Migration Events */
        get: operations["migration_events_api_migrations__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshot Profiles */
        get: operations["list_snapshot_profiles_api_snapshots_profiles_get"];
        put?: never;
        /** Create Snapshot Profile */
        post: operations["create_snapshot_profile_api_snapshots_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Snapshot Profile */
        delete: operations["delete_snapshot_profile_api_snapshots_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        /** Update Snapshot Profile */
        patch: operations["update_snapshot_profile_api_snapshots_profiles__profile_id__patch"];
        trace?: never;
    };
    "/api/snapshots/profiles/{profile_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Snapshot */
        post: operations["create_snapshot_api_snapshots_profiles__profile_id__snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/profiles/{profile_id}/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cleanup Snapshots */
        post: operations["cleanup_snapshots_api_snapshots_profiles__profile_id__cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Snapshot */
        post: operations["import_snapshot_api_snapshots_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        /** Delete Snapshot */
        delete: operations["delete_snapshot_api_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Snapshot */
        post: operations["verify_snapshot_api_snapshots__snapshot_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Snapshot */
        get: operations["diff_snapshot_api_snapshots__snapshot_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Snapshot */
        get: operations["download_snapshot_api_snapshots__snapshot_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountView */
        AccountView: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Provider User Id */
            provider_user_id?: string | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** AggregateMigrationStatsView */
        AggregateMigrationStatsView: {
            /** Source Provider */
            source_provider?: string | null;
            /** Target Provider */
            target_provider?: string | null;
            /**
             * Total Migrations
             * @default 0
             */
            total_migrations: number;
            /**
             * Total Playlists
             * @default 0
             */
            total_playlists: number;
            counts: components["schemas"]["StatusCounts"];
            /**
             * Empty
             * @default false
             */
            empty: boolean;
            /** Message */
            message?: string | null;
        };
        /** AuthChallenge */
        AuthChallenge: {
            shape: components["schemas"]["ChallengeShape"];
            /** Redirect Url */
            redirect_url?: string | null;
            /** State */
            state?: string | null;
            /** User Code */
            user_code?: string | null;
            /** Verification Url */
            verification_url?: string | null;
            /** Poll Interval S */
            poll_interval_s?: number | null;
            /** Instructions */
            instructions?: string | null;
            /** Form Schema */
            form_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /** BatchReview */
        BatchReview: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "skip";
            /**
             * Item Ids
             * @default []
             */
            item_ids: string[];
        };
        /**
         * ChallengeShape
         * @description The three UI shapes every auth flow collapses into.
         * @enum {string}
         */
        ChallengeShape: "redirect" | "device_code" | "form";
        /** ConnectionTestView */
        ConnectionTestView: {
            /** Status */
            status: string;
            /** Provider */
            provider: string;
            /** Account Id */
            account_id: string;
            /** Message */
            message: string;
        };
        /** ConnectionView */
        ConnectionView: {
            /** Status */
            status: string;
            /** Provider */
            provider: string;
            account: components["schemas"]["AccountView"];
        };
        /** CreateMigration */
        CreateMigration: {
            /** Source Provider */
            source_provider?: string | null;
            /** Target Provider */
            target_provider: string;
            /** Source Account Id */
            source_account_id?: string | null;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Target Account Id */
            target_account_id: string;
            selection: components["schemas"]["Selection"];
            /**
             * Acknowledge Warnings
             * @default false
             */
            acknowledge_warnings: boolean;
        };
        /** Credit */
        Credit: {
            /** Role */
            role: string;
            /** Name */
            name: string;
            /** Instrument */
            instrument?: string | null;
            /** Uri */
            uri?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobItemView */
        JobItemView: {
            /** Id */
            id: string;
            /** Source Playlist Id */
            source_playlist_id: string;
            /** Source Playlist Name */
            source_playlist_name?: string | null;
            /** Target Playlist Id */
            target_playlist_id?: string | null;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Release Year */
            release_year?: number | null;
            /** Explicit */
            explicit?: boolean | null;
            /** Isrc */
            isrc?: string | null;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: unknown;
            };
            /** Target Uri */
            target_uri?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
        };
        /** JobView */
        JobView: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /**
             * Source Kind
             * @default provider
             */
            source_kind: string;
            /** Source Provider */
            source_provider: string;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Target Provider */
            target_provider: string;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Error */
            error?: string | null;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "track" | "episode" | "video" | "local_file" | "unknown";
        /** MigrationOptionView */
        MigrationOptionView: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Playlist Names */
            playlist_names?: string[];
            /** Status */
            status: string;
            /** Source Provider */
            source_provider: string;
            /** Target Provider */
            target_provider: string;
            /** Created At */
            created_at?: string | null;
        };
        /** MigrationStatsView */
        MigrationStatsView: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Playlist Names */
            playlist_names?: string[];
            /** Status */
            status: string;
            /** Source Provider */
            source_provider: string;
            /** Target Provider */
            target_provider: string;
            /** Created At */
            created_at?: string | null;
            counts: components["schemas"]["StatusCounts"];
            /**
             * Playlist Count
             * @default 0
             */
            playlist_count: number;
            /** Playlists */
            playlists?: components["schemas"]["PlaylistStatsView"][];
            /**
             * Empty
             * @default false
             */
            empty: boolean;
            /** Message */
            message?: string | null;
        };
        /** MigrationWarningsView */
        MigrationWarningsView: {
            /**
             * Code
             * @default migration_warnings
             */
            code: string;
            /**
             * Message
             * @default Review and acknowledge migration warnings before starting.
             */
            message: string;
            /**
             * Warnings
             * @default []
             */
            warnings: {
                [key: string]: string;
            }[];
        };
        /** Playlist */
        Playlist: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Photo */
            photo?: string | null;
            /** Tracks */
            tracks?: components["schemas"]["Track"][];
            /** Owner Id */
            owner_id?: string | null;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** @default standard */
            kind: components["schemas"]["PlaylistKind"];
        };
        /**
         * PlaylistKind
         * @enum {string}
         */
        PlaylistKind: "standard" | "liked_tracks";
        /**
         * PlaylistRef
         * @description Lightweight handle returned while listing, before full read.
         */
        PlaylistRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Track Count */
            track_count?: number | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Collaborative */
            collaborative?: boolean | null;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /** Tracks Href */
            tracks_href?: string | null;
            /** Migration Status */
            migration_status?: string | null;
            /**
             * Migrated Track Count
             * @default 0
             */
            migrated_track_count: number;
            /** Remaining Track Count */
            remaining_track_count?: number | null;
            /** Migration Note */
            migration_note?: string | null;
            /** @default standard */
            kind: components["schemas"]["PlaylistKind"];
        };
        /** PlaylistStatsView */
        PlaylistStatsView: {
            /** Source Playlist Id */
            source_playlist_id: string;
            /** Source Playlist Name */
            source_playlist_name?: string | null;
            /** Target Playlist Id */
            target_playlist_id?: string | null;
            counts: components["schemas"]["StatusCounts"];
        };
        /** ProviderView */
        ProviderView: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Auth Kind */
            auth_kind: string;
            /** Official */
            official: boolean;
            /** Stability */
            stability: string;
            /** Has Isrc */
            has_isrc: boolean;
            /** Can Source */
            can_source: boolean;
            /** Can Target */
            can_target: boolean;
            /** Warning */
            warning?: string | null;
        };
        /** ReviewItem */
        ReviewItem: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "skip";
            /** Target Uri */
            target_uri?: string | null;
        };
        /** Selection */
        Selection: {
            /**
             * Playlist Ids
             * @default []
             */
            playlist_ids: string[];
            /**
             * Tracks
             * @default {}
             */
            tracks: {
                [key: string]: string[];
            };
        };
        /** SnapshotCleanupView */
        SnapshotCleanupView: {
            /** Deleted Count */
            deleted_count: number;
            /** Deleted Bytes */
            deleted_bytes: number;
        };
        /** SnapshotCollectionManifest */
        SnapshotCollectionManifest: {
            /** Id */
            id: string;
            /** Source Key */
            source_key: string;
            /** Source Provider */
            source_provider: string;
            /** Source Collection Id */
            source_collection_id: string;
            /**
             * Entity Type
             * @default playlist
             * @constant
             */
            entity_type: "playlist";
            /** Name */
            name: string;
            /** @default standard */
            kind: components["schemas"]["PlaylistKind"];
            /** Path */
            path: string;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /**
             * Payload Bytes
             * @default 0
             */
            payload_bytes: number;
            /** Payload Sha256 */
            payload_sha256: string;
            /** Items Sha256 */
            items_sha256: string;
            /**
             * Complete
             * @default true
             */
            complete: boolean;
            /** Error */
            error?: string | null;
        };
        /** SnapshotCounts */
        SnapshotCounts: {
            /**
             * Sources
             * @default 0
             */
            sources: number;
            /**
             * Collections
             * @default 0
             */
            collections: number;
            /**
             * Items
             * @default 0
             */
            items: number;
            /**
             * Failed Collections
             * @default 0
             */
            failed_collections: number;
        };
        /** SnapshotDetailView */
        SnapshotDetailView: {
            /** Id */
            id: string;
            /** Profile Id */
            profile_id?: string | null;
            /** Profile Name */
            profile_name?: string | null;
            /** Bundle Id */
            bundle_id: string;
            /** Library Id */
            library_id: string;
            /** Source Providers */
            source_providers?: string[];
            /** Source Labels */
            source_labels?: string[];
            /** Status */
            status: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            counts?: components["schemas"]["SnapshotCounts"];
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[];
            /** Verification Status */
            verification_status: string;
            /** Verification Error */
            verification_error?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /** Created At */
            created_at?: string | null;
            manifest?: components["schemas"]["SnapshotManifest"] | null;
        };
        /** SnapshotDiff */
        SnapshotDiff: {
            /** Base Snapshot Id */
            base_snapshot_id: string;
            /** Compare Snapshot Id */
            compare_snapshot_id: string;
            /** Added */
            added?: components["schemas"]["SnapshotDiffCollection"][];
            /** Removed */
            removed?: components["schemas"]["SnapshotDiffCollection"][];
            /** Renamed */
            renamed?: components["schemas"]["SnapshotDiffCollection"][];
            /** Changed */
            changed?: components["schemas"]["SnapshotDiffCollection"][];
            /**
             * Items Added
             * @default 0
             */
            items_added: number;
            /**
             * Items Removed
             * @default 0
             */
            items_removed: number;
        };
        /** SnapshotDiffCollection */
        SnapshotDiffCollection: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Previous Name */
            previous_name?: string | null;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /** Previous Item Count */
            previous_item_count?: number | null;
        };
        /** SnapshotFailure */
        SnapshotFailure: {
            /** Source Key */
            source_key: string;
            /** Provider */
            provider: string;
            /** Collection Id */
            collection_id?: string | null;
            /** Message */
            message: string;
        };
        /** SnapshotListView */
        SnapshotListView: {
            /** Snapshots */
            snapshots?: components["schemas"]["SnapshotView"][];
            /**
             * Total Bytes
             * @default 0
             */
            total_bytes: number;
        };
        /** SnapshotManifest */
        SnapshotManifest: {
            /**
             * Format
             * @default open-playlist-bundle
             * @constant
             */
            format: "open-playlist-bundle";
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Snapshot Id */
            snapshot_id: string;
            /** Library Id */
            library_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Profile Name */
            profile_name?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial";
            /** Sources */
            sources?: components["schemas"]["SnapshotSourceManifest"][];
            counts?: components["schemas"]["SnapshotCounts"];
            /** Collections */
            collections?: components["schemas"]["SnapshotCollectionManifest"][];
            /** Failures */
            failures?: components["schemas"]["SnapshotFailure"][];
        };
        /** SnapshotProfileCreate */
        SnapshotProfileCreate: {
            /** Name */
            name: string;
            /** Sources */
            sources: components["schemas"]["SnapshotProfileSourceInput"][];
            /** Retention Count */
            retention_count?: number | null;
            /** Retention Days */
            retention_days?: number | null;
        };
        /** SnapshotProfileSourceInput */
        SnapshotProfileSourceInput: {
            /** Provider */
            provider: string;
            /** Account Id */
            account_id: string;
            /** Collection Ids */
            collection_ids: string[];
        };
        /** SnapshotProfileSourceView */
        SnapshotProfileSourceView: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Account Id */
            account_id?: string | null;
            /** Account Label */
            account_label?: string | null;
            /** Collection Ids */
            collection_ids?: string[];
        };
        /** SnapshotProfileUpdate */
        SnapshotProfileUpdate: {
            /** Name */
            name?: string | null;
            /** Retention Count */
            retention_count?: number | null;
            /** Retention Days */
            retention_days?: number | null;
        };
        /** SnapshotProfileView */
        SnapshotProfileView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Retention Count */
            retention_count?: number | null;
            /** Retention Days */
            retention_days?: number | null;
            /** Sources */
            sources?: components["schemas"]["SnapshotProfileSourceView"][];
            /**
             * Snapshot Count
             * @default 0
             */
            snapshot_count: number;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SnapshotSourceManifest */
        SnapshotSourceManifest: {
            /** Key */
            key: string;
            /** Provider */
            provider: string;
            /** Account Label */
            account_label?: string | null;
            /**
             * Selected Collection Count
             * @default 0
             */
            selected_collection_count: number;
        };
        /** SnapshotVerificationView */
        SnapshotVerificationView: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Status */
            status: string;
            /** Archive Sha256 */
            archive_sha256?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** SnapshotView */
        SnapshotView: {
            /** Id */
            id: string;
            /** Profile Id */
            profile_id?: string | null;
            /** Profile Name */
            profile_name?: string | null;
            /** Bundle Id */
            bundle_id: string;
            /** Library Id */
            library_id: string;
            /** Source Providers */
            source_providers?: string[];
            /** Source Labels */
            source_labels?: string[];
            /** Status */
            status: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            counts?: components["schemas"]["SnapshotCounts"];
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[];
            /** Verification Status */
            verification_status: string;
            /** Verification Error */
            verification_error?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** StatusCounts */
        StatusCounts: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Matched
             * @default 0
             */
            matched: number;
            /**
             * Needs Review
             * @default 0
             */
            needs_review: number;
            /**
             * Written
             * @default 0
             */
            written: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Other */
            other?: {
                [key: string]: number;
            };
        };
        /**
         * Track
         * @description A single playlist item in universal form.
         *
         *     Only ``title`` and ``artist`` are strictly required; ``isrc`` is the primary
         *     cross-provider match key when present.
         */
        Track: {
            /** Id */
            id?: string | null;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Genre */
            genre?: string | null;
            /** Track Number */
            track_number?: number | null;
            /** Disc Number */
            disc_number?: number | null;
            /** Explicit */
            explicit?: boolean | null;
            /** Composer */
            composer?: string | null;
            /** Credits */
            credits?: components["schemas"]["Credit"][];
            /** Label */
            label?: string | null;
            /** Isrc */
            isrc?: string | null;
            /** Artwork Uri */
            artwork_uri?: string | null;
            /** Provider Uris */
            provider_uris?: {
                [key: string]: string;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Migration Status */
            migration_status?: string | null;
            /** Migrated Target Playlist Id */
            migrated_target_playlist_id?: string | null;
            /** Migrated Target Uri */
            migrated_target_uri?: string | null;
            /** Position */
            position?: number | null;
            /** @default track */
            media_type: components["schemas"]["MediaType"];
            /**
             * Is Local
             * @default false
             */
            is_local: boolean;
            /** Source Item Id */
            source_item_id?: string | null;
            /** Added At */
            added_at?: string | null;
            /** Unsupported Reason */
            unsupported_reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"][];
                };
            };
        };
    };
    begin_api_auth__provider__begin_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthChallenge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_api_auth_accounts_get: {
        parameters: {
            query?: {
                user_id?: string;
                provider?: string | null;
                check?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_account_connection_api_auth_accounts__account_id__test_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_api_auth__provider__complete_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_auth__provider__callback_get: {
        parameters: {
            query?: {
                user_id?: string;
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_playlists_api_playlists_get: {
        parameters: {
            query: {
                provider: string;
                account_id: string;
                target_provider?: string | null;
                target_account_id?: string | null;
                refresh?: boolean;
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playlist_api_playlists__playlist_id__get: {
        parameters: {
            query: {
                provider: string;
                account_id: string;
                target_provider?: string | null;
                target_account_id?: string | null;
                refresh?: boolean;
                user_id?: string;
            };
            header?: never;
            path: {
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_migrations_api_migrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationOptionView"][];
                };
            };
        };
    };
    create_migration_api_migrations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMigration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_migration_api_migrations_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMigration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationWarningsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aggregate_migration_stats_api_migrations_stats_get: {
        parameters: {
            query?: {
                source_provider?: string | null;
                target_provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateMigrationStatsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_migration_stats_api_migrations__job_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationStatsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_migration_api_migrations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_migration_items_api_migrations__job_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItemView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_migration_item_api_migrations__job_id__items__item_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewItem"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_migration_items_api_migrations__job_id__items_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItemView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    migration_events_api_migrations__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshot_profiles_api_snapshots_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotProfileView"][];
                };
            };
        };
    };
    create_snapshot_profile_api_snapshots_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_profile_api_snapshots_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_snapshot_profile_api_snapshots_profiles__profile_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_api_snapshots_profiles__profile_id__snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_snapshots_api_snapshots_profiles__profile_id__cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotCleanupView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_snapshot_api_snapshots_import_post: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/zip": string;
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDetailView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_snapshots_get: {
        parameters: {
            query?: {
                profile_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDetailView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_api_snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_snapshot_api_snapshots__snapshot_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotVerificationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_snapshot_api_snapshots__snapshot_id__diff_get: {
        parameters: {
            query: {
                base_snapshot_id: string;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_snapshot_api_snapshots__snapshot_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
